// All 64 districts of Bangladesh with their thanas / upazilas (English names).
export const DISTRICTS: Record<string, string[]> = {
  Bagerhat: ["Bagerhat Sadar", "Chitalmari", "Fakirhat", "Kachua", "Mollahat", "Mongla", "Morrelganj", "Rampal", "Sarankhola"],
  Bandarban: ["Alikadam", "Bandarban Sadar", "Lama", "Naikhongchhari", "Rowangchhari", "Ruma", "Thanchi"],
  Barguna: ["Amtali", "Bamna", "Barguna Sadar", "Betagi", "Patharghata", "Taltali"],
  Barisal: ["Agailjhara", "Babuganj", "Bakerganj", "Banaripara", "Barisal Sadar", "Gaurnadi", "Hizla", "Mehendiganj", "Muladi", "Wazirpur"],
  Bhola: ["Bhola Sadar", "Burhanuddin", "Char Fasson", "Daulatkhan", "Lalmohan", "Manpura", "Tazumuddin"],
  Bogura: ["Adamdighi", "Bogura Sadar", "Dhunat", "Dhupchanchia", "Gabtali", "Kahaloo", "Nandigram", "Sariakandi", "Shajahanpur", "Sherpur", "Shibganj", "Sonatala"],
  Brahmanbaria: ["Akhaura", "Ashuganj", "Bancharampur", "Bijoynagar", "Brahmanbaria Sadar", "Kasba", "Nabinagar", "Nasirnagar", "Sarail"],
  Chandpur: ["Chandpur Sadar", "Faridganj", "Haimchar", "Haziganj", "Kachua", "Matlab Dakshin", "Matlab Uttar", "Shahrasti"],
  Chapainawabganj: ["Bholahat", "Gomastapur", "Nachole", "Chapainawabganj Sadar", "Shibganj"],
  Chattogram: ["Anwara", "Banshkhali", "Boalkhali", "Chandanaish", "Fatikchhari", "Hathazari", "Lohagara", "Mirsharai", "Patiya", "Rangunia", "Raozan", "Sandwip", "Satkania", "Sitakunda", "Chattogram City"],
  Chuadanga: ["Alamdanga", "Chuadanga Sadar", "Damurhuda", "Jibannagar"],
  Comilla: ["Barura", "Brahmanpara", "Burichang", "Chandina", "Chauddagram", "Comilla Sadar", "Daudkandi", "Debidwar", "Homna", "Laksam", "Meghna", "Monohorganj", "Muradnagar", "Nangalkot", "Titas"],
  "Cox's Bazar": ["Chakaria", "Cox's Bazar Sadar", "Kutubdia", "Maheshkhali", "Pekua", "Ramu", "Teknaf", "Ukhia"],
  Dhaka: ["Adabor", "Badda", "Banani", "Cantonment", "Dhanmondi", "Dakshinkhan", "Demra", "Gulshan", "Hazaribagh", "Jatrabari", "Kafrul", "Kamrangirchar", "Khilgaon", "Khilkhet", "Lalbagh", "Mirpur", "Mohammadpur", "Motijheel", "Pallabi", "Ramna", "Rampura", "Sabujbagh", "Shahbagh", "Sher-e-Bangla Nagar", "Shyampur", "Tejgaon", "Turag", "Uttara", "Uttarkhan", "Vatara", "Wari", "Dhamrai", "Dohar", "Keraniganj", "Nawabganj", "Savar"],
  Dinajpur: ["Birampur", "Birganj", "Biral", "Bochaganj", "Chirirbandar", "Dinajpur Sadar", "Ghoraghat", "Hakimpur", "Kaharole", "Khansama", "Nawabganj", "Parbatipur", "Phulbari"],
  Faridpur: ["Alfadanga", "Bhanga", "Boalmari", "Charbhadrasan", "Faridpur Sadar", "Madhukhali", "Nagarkanda", "Sadarpur", "Saltha"],
  Feni: ["Chhagalnaiya", "Daganbhuiyan", "Feni Sadar", "Fulgazi", "Parshuram", "Sonagazi"],
  Gaibandha: ["Fulchhari", "Gaibandha Sadar", "Gobindaganj", "Palashbari", "Sadullapur", "Saghata", "Sundarganj"],
  Gazipur: ["Gazipur Sadar", "Kaliakair", "Kaliganj", "Kapasia", "Sreepur", "Tongi"],
  Gopalganj: ["Gopalganj Sadar", "Kashiani", "Kotalipara", "Muksudpur", "Tungipara"],
  Habiganj: ["Ajmiriganj", "Bahubal", "Baniyachong", "Chunarughat", "Habiganj Sadar", "Lakhai", "Madhabpur", "Nabiganj", "Shayestaganj"],
  Jamalpur: ["Baksiganj", "Dewanganj", "Islampur", "Jamalpur Sadar", "Madarganj", "Melandaha", "Sarishabari"],
  Jashore: ["Abhaynagar", "Bagherpara", "Chaugachha", "Jhikargachha", "Keshabpur", "Jashore Sadar", "Manirampur", "Sharsha"],
  Jhalokati: ["Jhalokati Sadar", "Kathalia", "Nalchity", "Rajapur"],
  Jhenaidah: ["Harinakunda", "Jhenaidah Sadar", "Kaliganj", "Kotchandpur", "Maheshpur", "Shailkupa"],
  Joypurhat: ["Akkelpur", "Joypurhat Sadar", "Kalai", "Khetlal", "Panchbibi"],
  Khagrachhari: ["Dighinala", "Khagrachhari Sadar", "Lakshmichhari", "Mahalchhari", "Manikchhari", "Matiranga", "Panchhari", "Ramgarh"],
  Khulna: ["Batiaghata", "Dacope", "Dumuria", "Dighalia", "Koyra", "Paikgachha", "Phultala", "Rupsha", "Terokhada", "Khulna City"],
  Kishoreganj: ["Austagram", "Bajitpur", "Bhairab", "Hossainpur", "Itna", "Karimganj", "Katiadi", "Kishoreganj Sadar", "Kuliarchar", "Mithamain", "Nikli", "Pakundia", "Tarail"],
  Kurigram: ["Bhurungamari", "Char Rajibpur", "Chilmari", "Kurigram Sadar", "Nageshwari", "Phulbari", "Rajarhat", "Raumari", "Ulipur"],
  Kushtia: ["Bheramara", "Daulatpur", "Khoksa", "Kumarkhali", "Kushtia Sadar", "Mirpur"],
  Lakshmipur: ["Kamalnagar", "Lakshmipur Sadar", "Raipur", "Ramganj", "Ramgati"],
  Lalmonirhat: ["Aditmari", "Hatibandha", "Kaliganj", "Lalmonirhat Sadar", "Patgram"],
  Madaripur: ["Kalkini", "Madaripur Sadar", "Rajoir", "Shibchar"],
  Magura: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
  Manikganj: ["Daulatpur", "Ghior", "Harirampur", "Manikganj Sadar", "Saturia", "Shibalaya", "Singair"],
  Meherpur: ["Gangni", "Meherpur Sadar", "Mujibnagar"],
  Moulvibazar: ["Barlekha", "Juri", "Kamalganj", "Kulaura", "Moulvibazar Sadar", "Rajnagar", "Sreemangal"],
  Munshiganj: ["Gazaria", "Lohajang", "Munshiganj Sadar", "Sirajdikhan", "Sreenagar", "Tongibari"],
  Mymensingh: ["Bhaluka", "Dhobaura", "Fulbaria", "Gaffargaon", "Gauripur", "Haluaghat", "Ishwarganj", "Muktagachha", "Mymensingh Sadar", "Nandail", "Phulpur", "Tarakanda", "Trishal"],
  Naogaon: ["Atrai", "Badalgachhi", "Dhamoirhat", "Manda", "Mahadebpur", "Naogaon Sadar", "Niamatpur", "Patnitala", "Porsha", "Raninagar", "Sapahar"],
  Narail: ["Kalia", "Lohagara", "Narail Sadar"],
  Narayanganj: ["Araihazar", "Bandar", "Narayanganj Sadar", "Rupganj", "Sonargaon"],
  Narsingdi: ["Belabo", "Monohardi", "Narsingdi Sadar", "Palash", "Raipura", "Shibpur"],
  Natore: ["Bagatipara", "Baraigram", "Gurudaspur", "Lalpur", "Natore Sadar", "Naldanga", "Singra"],
  Netrokona: ["Atpara", "Barhatta", "Durgapur", "Kalmakanda", "Kendua", "Khaliajuri", "Madan", "Mohanganj", "Netrokona Sadar", "Purbadhala"],
  Nilphamari: ["Dimla", "Domar", "Jaldhaka", "Kishoreganj", "Nilphamari Sadar", "Saidpur"],
  Noakhali: ["Begumganj", "Chatkhil", "Companiganj", "Hatiya", "Kabirhat", "Noakhali Sadar", "Senbagh", "Sonaimuri", "Subarnachar"],
  Pabna: ["Atgharia", "Bera", "Bhangura", "Chatmohar", "Faridpur", "Ishwardi", "Pabna Sadar", "Santhia", "Sujanagar"],
  Panchagarh: ["Atwari", "Boda", "Debiganj", "Panchagarh Sadar", "Tetulia"],
  Patuakhali: ["Bauphal", "Dashmina", "Dumki", "Galachipa", "Kalapara", "Mirzaganj", "Patuakhali Sadar", "Rangabali"],
  Pirojpur: ["Bhandaria", "Kawkhali", "Mathbaria", "Nazirpur", "Nesarabad", "Pirojpur Sadar", "Zianagar"],
  Rajbari: ["Baliakandi", "Goalandaghat", "Kalukhali", "Pangsha", "Rajbari Sadar"],
  Rajshahi: ["Bagha", "Bagmara", "Charghat", "Durgapur", "Godagari", "Mohanpur", "Paba", "Puthia", "Tanore", "Rajshahi City"],
  Rangamati: ["Baghaichhari", "Barkal", "Belaichhari", "Kaptai", "Juraichhari", "Langadu", "Naniarchar", "Rajasthali", "Rangamati Sadar"],
  Rangpur: ["Badarganj", "Gangachara", "Kaunia", "Mithapukur", "Pirgachha", "Pirganj", "Rangpur Sadar", "Taraganj"],
  Satkhira: ["Assasuni", "Debhata", "Kalaroa", "Kaliganj", "Satkhira Sadar", "Shyamnagar", "Tala"],
  Shariatpur: ["Bhedarganj", "Damudya", "Gosairhat", "Naria", "Shariatpur Sadar", "Zanjira"],
  Sherpur: ["Jhenaigati", "Nakla", "Nalitabari", "Sherpur Sadar", "Sreebardi"],
  Sirajganj: ["Belkuchi", "Chauhali", "Kamarkhanda", "Kazipur", "Raiganj", "Shahjadpur", "Sirajganj Sadar", "Tarash", "Ullapara"],
  Sunamganj: ["Bishwamberpur", "Chhatak", "Derai", "Dharampasha", "Dowarabazar", "Jagannathpur", "Jamalganj", "Sullah", "Sunamganj Sadar", "Tahirpur"],
  Sylhet: ["Balaganj", "Beanibazar", "Bishwanath", "Companiganj", "Fenchuganj", "Golapganj", "Gowainghat", "Jaintiapur", "Kanaighat", "Osmani Nagar", "Sylhet Sadar", "Zakiganj"],
  Tangail: ["Basail", "Bhuapur", "Delduar", "Dhanbari", "Ghatail", "Gopalpur", "Kalihati", "Madhupur", "Mirzapur", "Nagarpur", "Sakhipur", "Tangail Sadar"],
  Thakurgaon: ["Baliadangi", "Haripur", "Pirganj", "Ranisankail", "Thakurgaon Sadar"],
};

export const DISTRICT_NAMES = Object.keys(DISTRICTS).sort();

/** Bengali display names; English keys remain the canonical values saved with orders. */
export const DISTRICT_BN: Record<string, string> = {
  "Bagerhat": "বাগেরহাট",
  "Bandarban": "বান্দরবান",
  "Barguna": "বরগুনা",
  "Barisal": "বরিশাল",
  "Bhola": "ভোলা",
  "Bogura": "বগুড়া",
  "Brahmanbaria": "ব্রাহ্মণবাড়িয়া",
  "Chandpur": "চাঁদপুর",
  "Chapainawabganj": "চাঁপাইনবাবগঞ্জ",
  "Chattogram": "চট্টগ্রাম",
  "Chuadanga": "চুয়াডাঙ্গা",
  "Comilla": "কুমিল্লা",
  "Cox's Bazar": "কক্সবাজার",
  "Dhaka": "ঢাকা",
  "Dinajpur": "দিনাজপুর",
  "Faridpur": "ফরিদপুর",
  "Feni": "ফেনী",
  "Gaibandha": "গাইবান্ধা",
  "Gazipur": "গাজীপুর",
  "Gopalganj": "গোপালগঞ্জ",
  "Habiganj": "হবিগঞ্জ",
  "Jamalpur": "জামালপুর",
  "Jashore": "যশোর",
  "Jhalokati": "ঝালকাঠি",
  "Jhenaidah": "ঝিনাইদহ",
  "Joypurhat": "জয়পুরহাট",
  "Khagrachhari": "খাগড়াছড়ি",
  "Khulna": "খুলনা",
  "Kishoreganj": "কিশোরগঞ্জ",
  "Kurigram": "কুড়িগ্রাম",
  "Kushtia": "কুষ্টিয়া",
  "Lakshmipur": "লক্ষ্মীপুর",
  "Lalmonirhat": "লালমনিরহাট",
  "Madaripur": "মাদারীপুর",
  "Magura": "মাগুরা",
  "Manikganj": "মানিকগঞ্জ",
  "Meherpur": "মেহেরপুর",
  "Moulvibazar": "মৌলভীবাজার",
  "Munshiganj": "মুন্সিগঞ্জ",
  "Mymensingh": "ময়মনসিংহ",
  "Naogaon": "নওগাঁ",
  "Narail": "নড়াইল",
  "Narayanganj": "নারায়ণগঞ্জ",
  "Narsingdi": "নরসিংদী",
  "Natore": "নাটোর",
  "Netrokona": "নেত্রকোণা",
  "Nilphamari": "নীলফামারী",
  "Noakhali": "নোয়াখালী",
  "Pabna": "পাবনা",
  "Panchagarh": "পঞ্চগড়",
  "Patuakhali": "পটুয়াখালী",
  "Pirojpur": "পিরোজপুর",
  "Rajbari": "রাজবাড়ী",
  "Rajshahi": "রাজশাহী",
  "Rangamati": "রাঙ্গামাটি",
  "Rangpur": "রংপুর",
  "Satkhira": "সাতক্ষীরা",
  "Shariatpur": "শরীয়তপুর",
  "Sherpur": "শেরপুর",
  "Sirajganj": "সিরাজগঞ্জ",
  "Sunamganj": "সুনামগঞ্জ",
  "Sylhet": "সিলেট",
  "Tangail": "টাঙ্গাইল",
  "Thakurgaon": "ঠাকুরগাঁও"
};

const THANA_BN: Record<string, string> = {
  "Bagerhat:Bagerhat Sadar": "বাগেরহাট সদর",
  "Bagerhat:Chitalmari": "চিতলমারী",
  "Bagerhat:Fakirhat": "ফকিরহাট",
  "Bagerhat:Kachua": "কচুয়া",
  "Bagerhat:Mollahat": "মোল্লাহাট",
  "Bagerhat:Mongla": "মোংলা",
  "Bagerhat:Morrelganj": "মোড়েলগঞ্জ",
  "Bagerhat:Rampal": "রামপাল",
  "Bagerhat:Sarankhola": "শরণখোলা",
  "Bandarban:Alikadam": "আলীকদম",
  "Bandarban:Bandarban Sadar": "বান্দরবান সদর",
  "Bandarban:Lama": "লামা",
  "Bandarban:Naikhongchhari": "নাইক্ষ্যংছড়ি",
  "Bandarban:Rowangchhari": "রোয়াংছড়ি",
  "Bandarban:Ruma": "রুমা",
  "Bandarban:Thanchi": "থানচি",
  "Barguna:Amtali": "আমতলী",
  "Barguna:Bamna": "বামনা",
  "Barguna:Barguna Sadar": "বরগুনা সদর",
  "Barguna:Betagi": "বেতাগী",
  "Barguna:Patharghata": "পাথরঘাটা",
  "Barguna:Taltali": "তালতলি",
  "Barisal:Agailjhara": "আগৈলঝাড়া",
  "Barisal:Babuganj": "বাবুগঞ্জ",
  "Barisal:Bakerganj": "বাকেরগঞ্জ",
  "Barisal:Banaripara": "বানারীপাড়া",
  "Barisal:Barisal Sadar": "বরিশাল সদর",
  "Barisal:Gaurnadi": "গৌরনদী",
  "Barisal:Hizla": "হিজলা",
  "Barisal:Mehendiganj": "মেহেন্দিগঞ্জ",
  "Barisal:Muladi": "মুলাদী",
  "Barisal:Wazirpur": "উজিরপুর",
  "Bhola:Bhola Sadar": "ভোলা সদর",
  "Bhola:Burhanuddin": "বোরহান উদ্দিন",
  "Bhola:Char Fasson": "চরফ্যাশন",
  "Bhola:Daulatkhan": "দৌলতখান",
  "Bhola:Lalmohan": "লালমোহন",
  "Bhola:Manpura": "মনপুরা",
  "Bhola:Tazumuddin": "তজুমদ্দিন",
  "Bogura:Adamdighi": "আদমদিঘি",
  "Bogura:Bogura Sadar": "বগুড়া সদর",
  "Bogura:Dhunat": "ধুনট",
  "Bogura:Dhupchanchia": "দুপচাচিঁয়া",
  "Bogura:Gabtali": "গাবতলী",
  "Bogura:Kahaloo": "কাহালু",
  "Bogura:Nandigram": "নন্দিগ্রাম",
  "Bogura:Sariakandi": "সারিয়াকান্দি",
  "Bogura:Shajahanpur": "শাজাহানপুর",
  "Bogura:Sherpur": "শেরপুর",
  "Bogura:Shibganj": "শিবগঞ্জ",
  "Bogura:Sonatala": "সোনাতলা",
  "Brahmanbaria:Akhaura": "আখাউড়া",
  "Brahmanbaria:Ashuganj": "আশুগঞ্জ",
  "Brahmanbaria:Bancharampur": "বাঞ্ছারামপুর",
  "Brahmanbaria:Bijoynagar": "বিজয়নগর",
  "Brahmanbaria:Brahmanbaria Sadar": "ব্রাহ্মণবাড়িয়া সদর",
  "Brahmanbaria:Kasba": "কসবা",
  "Brahmanbaria:Nabinagar": "নবীনগর",
  "Brahmanbaria:Nasirnagar": "নাসিরনগর",
  "Brahmanbaria:Sarail": "সরাইল",
  "Chandpur:Chandpur Sadar": "চাঁদপুর সদর",
  "Chandpur:Faridganj": "ফরিদগঞ্জ",
  "Chandpur:Haimchar": "হাইমচর",
  "Chandpur:Haziganj": "হাজীগঞ্জ",
  "Chandpur:Kachua": "কচুয়া",
  "Chandpur:Matlab Dakshin": "মতলব দক্ষিণ",
  "Chandpur:Matlab Uttar": "মতলব দক্ষিণ",
  "Chandpur:Shahrasti": "শাহরাস্তি\t",
  "Chapainawabganj:Bholahat": "ভোলাহাট",
  "Chapainawabganj:Gomastapur": "গোমস্তাপুর",
  "Chapainawabganj:Nachole": "নাচোল",
  "Chapainawabganj:Chapainawabganj Sadar": "চাঁপাইনবাবগঞ্জ সদর",
  "Chapainawabganj:Shibganj": "শিবগঞ্জ",
  "Chattogram:Anwara": "আনোয়ারা",
  "Chattogram:Banshkhali": "বাঁশখালী",
  "Chattogram:Boalkhali": "বোয়ালখালী",
  "Chattogram:Chandanaish": "চন্দনাইশ",
  "Chattogram:Fatikchhari": "ফটিকছড়ি",
  "Chattogram:Hathazari": "হাটহাজারী",
  "Chattogram:Lohagara": "লোহাগাড়া",
  "Chattogram:Mirsharai": "মীরসরাই",
  "Chattogram:Patiya": "পটিয়া",
  "Chattogram:Rangunia": "রাঙ্গুনিয়া",
  "Chattogram:Raozan": "রাউজান",
  "Chattogram:Sandwip": "সন্দ্বীপ",
  "Chattogram:Satkania": "সাতকানিয়া",
  "Chattogram:Sitakunda": "সীতাকুন্ড",
  "Chattogram:Chattogram City": "চট্টগ্রাম সিটি",
  "Chuadanga:Alamdanga": "আলমডাঙ্গা",
  "Chuadanga:Chuadanga Sadar": "চুয়াডাঙ্গা সদর",
  "Chuadanga:Damurhuda": "দামুড়হুদা",
  "Chuadanga:Jibannagar": "জীবননগর",
  "Comilla:Barura": "বরুড়া",
  "Comilla:Brahmanpara": "ব্রাহ্মণপাড়া",
  "Comilla:Burichang": "বুড়িচং",
  "Comilla:Chandina": "চান্দিনা",
  "Comilla:Chauddagram": "চৌদ্দগ্রাম",
  "Comilla:Comilla Sadar": "কুমিল্লা সদর",
  "Comilla:Daudkandi": "দাউদকান্দি",
  "Comilla:Debidwar": "দেবিদ্বার",
  "Comilla:Homna": "হোমনা",
  "Comilla:Laksam": "লাকসাম",
  "Comilla:Meghna": "মেঘনা",
  "Comilla:Monohorganj": "মনোহরগঞ্জ",
  "Comilla:Muradnagar": "মুরাদনগর",
  "Comilla:Nangalkot": "নাঙ্গলকোট",
  "Comilla:Titas": "তিতাস",
  "Cox's Bazar:Chakaria": "চকরিয়া",
  "Cox's Bazar:Cox's Bazar Sadar": "কক্সবাজার সদর",
  "Cox's Bazar:Kutubdia": "কুতুবদিয়া",
  "Cox's Bazar:Maheshkhali": "মহেশখালী",
  "Cox's Bazar:Pekua": "পেকুয়া",
  "Cox's Bazar:Ramu": "রামু",
  "Cox's Bazar:Teknaf": "টেকনাফ",
  "Cox's Bazar:Ukhia": "উখিয়া",
  "Dhaka:Adabor": "আদাবর",
  "Dhaka:Badda": "বাড্ডা",
  "Dhaka:Banani": "বনানী",
  "Dhaka:Cantonment": "ক্যান্টনমেন্ট",
  "Dhaka:Dhanmondi": "ধানমন্ডি",
  "Dhaka:Dakshinkhan": "দক্ষিণখান",
  "Dhaka:Demra": "ডেমরা",
  "Dhaka:Gulshan": "গুলশান",
  "Dhaka:Hazaribagh": "হাজারীবাগ",
  "Dhaka:Jatrabari": "যাত্রাবাড়ী",
  "Dhaka:Kafrul": "কাফরুল",
  "Dhaka:Kamrangirchar": "কামরাঙ্গীরচর",
  "Dhaka:Khilgaon": "খিলগাঁও",
  "Dhaka:Khilkhet": "খিলক্ষেত",
  "Dhaka:Lalbagh": "লালবাগ",
  "Dhaka:Mirpur": "মিরপুর",
  "Dhaka:Mohammadpur": "মোহাম্মদপুর",
  "Dhaka:Motijheel": "মতিঝিল",
  "Dhaka:Pallabi": "পল্লবী",
  "Dhaka:Ramna": "রমনা",
  "Dhaka:Rampura": "রামপুরা",
  "Dhaka:Sabujbagh": "সবুজবাগ",
  "Dhaka:Shahbagh": "শাহবাগ",
  "Dhaka:Sher-e-Bangla Nagar": "শেরেবাংলা নগর",
  "Dhaka:Shyampur": "শ্যামপুর",
  "Dhaka:Tejgaon": "তেজগাঁও",
  "Dhaka:Turag": "তুরাগ",
  "Dhaka:Uttara": "উত্তরা",
  "Dhaka:Uttarkhan": "উত্তরখান",
  "Dhaka:Vatara": "ভাটারা",
  "Dhaka:Wari": "ওয়ারী",
  "Dhaka:Dhamrai": "ধামরাই",
  "Dhaka:Dohar": "দোহার",
  "Dhaka:Keraniganj": "কেরাণীগঞ্জ",
  "Dhaka:Nawabganj": "নবাবগঞ্জ",
  "Dhaka:Savar": "সাভার",
  "Dinajpur:Birampur": "বিরামপুর",
  "Dinajpur:Birganj": "বীরগঞ্জ",
  "Dinajpur:Biral": "বিরল",
  "Dinajpur:Bochaganj": "বোচাগঞ্জ",
  "Dinajpur:Chirirbandar": "চিরিরবন্দর",
  "Dinajpur:Dinajpur Sadar": "দিনাজপুর সদর",
  "Dinajpur:Ghoraghat": "ঘোড়াঘাট",
  "Dinajpur:Hakimpur": "হাকিমপুর",
  "Dinajpur:Kaharole": "কাহারোল",
  "Dinajpur:Khansama": "খানসামা",
  "Dinajpur:Nawabganj": "নবাবগঞ্জ",
  "Dinajpur:Parbatipur": "পার্বতীপুর",
  "Dinajpur:Phulbari": "ফুলবাড়ী",
  "Faridpur:Alfadanga": "আলফাডাঙ্গা",
  "Faridpur:Bhanga": "ভাঙ্গা",
  "Faridpur:Boalmari": "বোয়ালমারী",
  "Faridpur:Charbhadrasan": "চরভদ্রাসন",
  "Faridpur:Faridpur Sadar": "ফরিদপুর সদর",
  "Faridpur:Madhukhali": "মধুখালী",
  "Faridpur:Nagarkanda": "নগরকান্দা",
  "Faridpur:Sadarpur": "সদরপুর",
  "Faridpur:Saltha": "সালথা",
  "Feni:Chhagalnaiya": "ছাগলনাইয়া",
  "Feni:Daganbhuiyan": "দাগনভূঞা",
  "Feni:Feni Sadar": "ফেনী সদর",
  "Feni:Fulgazi": "ফুলগাজী",
  "Feni:Parshuram": "পরশুরাম",
  "Feni:Sonagazi": "সোনাগাজী",
  "Gaibandha:Fulchhari": "ফুলছড়ি",
  "Gaibandha:Gaibandha Sadar": "গাইবান্ধা সদর",
  "Gaibandha:Gobindaganj": "গোবিন্দগঞ্জ",
  "Gaibandha:Palashbari": "পলাশবাড়ী",
  "Gaibandha:Sadullapur": "সাদুল্লাপুর",
  "Gaibandha:Saghata": "সাঘাটা",
  "Gaibandha:Sundarganj": "সুন্দরগঞ্জ",
  "Gazipur:Gazipur Sadar": "গাজীপুর সদর",
  "Gazipur:Kaliakair": "কালিয়াকৈর",
  "Gazipur:Kaliganj": "কালীগঞ্জ",
  "Gazipur:Kapasia": "কাপাসিয়া",
  "Gazipur:Sreepur": "শ্রীপুর",
  "Gazipur:Tongi": "টঙ্গী",
  "Gopalganj:Gopalganj Sadar": "গোপালগঞ্জ সদর",
  "Gopalganj:Kashiani": "কাশিয়ানী",
  "Gopalganj:Kotalipara": "কোটালীপাড়া",
  "Gopalganj:Muksudpur": "মুকসুদপুর",
  "Gopalganj:Tungipara": "টুংগীপাড়া",
  "Habiganj:Ajmiriganj": "আজমিরীগঞ্জ",
  "Habiganj:Bahubal": "বাহুবল",
  "Habiganj:Baniyachong": "বানিয়াচং",
  "Habiganj:Chunarughat": "চুনারুঘাট",
  "Habiganj:Habiganj Sadar": "হবিগঞ্জ সদর",
  "Habiganj:Lakhai": "লাখাই",
  "Habiganj:Madhabpur": "মাধবপুর",
  "Habiganj:Nabiganj": "নবীগঞ্জ",
  "Habiganj:Shayestaganj": "শায়েস্তাগঞ্জ",
  "Jamalpur:Baksiganj": "বকশীগঞ্জ",
  "Jamalpur:Dewanganj": "দেওয়ানগঞ্জ",
  "Jamalpur:Islampur": "ইসলামপুর",
  "Jamalpur:Jamalpur Sadar": "জামালপুর সদর",
  "Jamalpur:Madarganj": "মাদারগঞ্জ",
  "Jamalpur:Melandaha": "মেলান্দহ",
  "Jamalpur:Sarishabari": "সরিষাবাড়ী",
  "Jashore:Abhaynagar": "অভয়নগর",
  "Jashore:Bagherpara": "বাঘারপাড়া",
  "Jashore:Chaugachha": "চৌগাছা",
  "Jashore:Jhikargachha": "ঝিকরগাছা",
  "Jashore:Keshabpur": "কেশবপুর",
  "Jashore:Jashore Sadar": "যশোর সদর",
  "Jashore:Manirampur": "মণিরামপুর",
  "Jashore:Sharsha": "শার্শা",
  "Jhalokati:Jhalokati Sadar": "ঝালকাঠি সদর",
  "Jhalokati:Kathalia": "কাঠালিয়া",
  "Jhalokati:Nalchity": "নলছিটি",
  "Jhalokati:Rajapur": "রাজাপুর",
  "Jhenaidah:Harinakunda": "হরিণাকুন্ডু",
  "Jhenaidah:Jhenaidah Sadar": "ঝিনাইদহ সদর",
  "Jhenaidah:Kaliganj": "কালীগঞ্জ",
  "Jhenaidah:Kotchandpur": "কোটচাঁদপুর",
  "Jhenaidah:Maheshpur": "মহেশপুর",
  "Jhenaidah:Shailkupa": "শৈলকুপা",
  "Joypurhat:Akkelpur": "আক্কেলপুর",
  "Joypurhat:Joypurhat Sadar": "জয়পুরহাট সদর",
  "Joypurhat:Kalai": "কালাই",
  "Joypurhat:Khetlal": "ক্ষেতলাল",
  "Joypurhat:Panchbibi": "পাঁচবিবি",
  "Khagrachhari:Dighinala": "দিঘীনালা",
  "Khagrachhari:Khagrachhari Sadar": "খাগড়াছড়ি সদর",
  "Khagrachhari:Lakshmichhari": "লক্ষীছড়ি",
  "Khagrachhari:Mahalchhari": "মহালছড়ি",
  "Khagrachhari:Manikchhari": "মানিকছড়ি",
  "Khagrachhari:Matiranga": "মাটিরাঙ্গা",
  "Khagrachhari:Panchhari": "পানছড়ি",
  "Khagrachhari:Ramgarh": "রামগড়",
  "Khulna:Batiaghata": "বটিয়াঘাটা",
  "Khulna:Dacope": "দাকোপ",
  "Khulna:Dumuria": "ডুমুরিয়া",
  "Khulna:Dighalia": "দিঘলিয়া",
  "Khulna:Koyra": "কয়রা",
  "Khulna:Paikgachha": "পাইকগাছা",
  "Khulna:Phultala": "ফুলতলা",
  "Khulna:Rupsha": "রূপসা",
  "Khulna:Terokhada": "তেরখাদা",
  "Khulna:Khulna City": "খুলনা সিটি",
  "Kishoreganj:Austagram": "অষ্টগ্রাম",
  "Kishoreganj:Bajitpur": "বাজিতপুর",
  "Kishoreganj:Bhairab": "ভৈরব",
  "Kishoreganj:Hossainpur": "হোসেনপুর",
  "Kishoreganj:Itna": "ইটনা",
  "Kishoreganj:Karimganj": "করিমগঞ্জ",
  "Kishoreganj:Katiadi": "কটিয়াদী",
  "Kishoreganj:Kishoreganj Sadar": "কিশোরগঞ্জ সদর",
  "Kishoreganj:Kuliarchar": "কুলিয়ারচর",
  "Kishoreganj:Mithamain": "মিঠামইন",
  "Kishoreganj:Nikli": "নিকলী",
  "Kishoreganj:Pakundia": "পাকুন্দিয়া",
  "Kishoreganj:Tarail": "তাড়াইল",
  "Kurigram:Bhurungamari": "ভুরুঙ্গামারী",
  "Kurigram:Char Rajibpur": "চর রাজিবপুর",
  "Kurigram:Chilmari": "চিলমারী",
  "Kurigram:Kurigram Sadar": "কুড়িগ্রাম সদর",
  "Kurigram:Nageshwari": "নাগেশ্বরী",
  "Kurigram:Phulbari": "ফুলবাড়ী",
  "Kurigram:Rajarhat": "রাজারহাট",
  "Kurigram:Raumari": "রৌমারী",
  "Kurigram:Ulipur": "উলিপুর",
  "Kushtia:Bheramara": "ভেড়ামারা",
  "Kushtia:Daulatpur": "দৌলতপুর",
  "Kushtia:Khoksa": "খোকসা",
  "Kushtia:Kumarkhali": "কুমারখালী",
  "Kushtia:Kushtia Sadar": "কুষ্টিয়া সদর",
  "Kushtia:Mirpur": "মিরপুর",
  "Lakshmipur:Kamalnagar": "কমলনগর",
  "Lakshmipur:Lakshmipur Sadar": "লক্ষ্মীপুর সদর",
  "Lakshmipur:Raipur": "রায়পুর",
  "Lakshmipur:Ramganj": "রামগঞ্জ",
  "Lakshmipur:Ramgati": "রামগতি",
  "Lalmonirhat:Aditmari": "আদিতমারী",
  "Lalmonirhat:Hatibandha": "হাতীবান্ধা",
  "Lalmonirhat:Kaliganj": "কালীগঞ্জ",
  "Lalmonirhat:Lalmonirhat Sadar": "লালমনিরহাট সদর",
  "Lalmonirhat:Patgram": "পাটগ্রাম",
  "Madaripur:Kalkini": "কালকিনি",
  "Madaripur:Madaripur Sadar": "মাদারীপুর সদর",
  "Madaripur:Rajoir": "রাজৈর",
  "Madaripur:Shibchar": "শিবচর",
  "Magura:Magura Sadar": "মাগুরা সদর",
  "Magura:Mohammadpur": "মহম্মদপুর",
  "Magura:Shalikha": "শালিখা",
  "Magura:Sreepur": "শ্রীপুর",
  "Manikganj:Daulatpur": "দৌলতপুর",
  "Manikganj:Ghior": "ঘিওর",
  "Manikganj:Harirampur": "হরিরামপুর",
  "Manikganj:Manikganj Sadar": "মানিকগঞ্জ সদর",
  "Manikganj:Saturia": "সাটুরিয়া",
  "Manikganj:Shibalaya": "শিবালয়",
  "Manikganj:Singair": "সিংগাইর",
  "Meherpur:Gangni": "গাংনী",
  "Meherpur:Meherpur Sadar": "মেহেরপুর সদর",
  "Meherpur:Mujibnagar": "মুজিবনগর",
  "Moulvibazar:Barlekha": "বড়লেখা",
  "Moulvibazar:Juri": "জুড়ী",
  "Moulvibazar:Kamalganj": "কমলগঞ্জ",
  "Moulvibazar:Kulaura": "কুলাউড়া",
  "Moulvibazar:Moulvibazar Sadar": "মৌলভীবাজার সদর",
  "Moulvibazar:Rajnagar": "রাজনগর",
  "Moulvibazar:Sreemangal": "শ্রীমঙ্গল",
  "Munshiganj:Gazaria": "গজারিয়া",
  "Munshiganj:Lohajang": "লৌহজং",
  "Munshiganj:Munshiganj Sadar": "মুন্সিগঞ্জ সদর",
  "Munshiganj:Sirajdikhan": "সিরাজদিখান",
  "Munshiganj:Sreenagar": "শ্রীনগর",
  "Munshiganj:Tongibari": "টংগীবাড়ি",
  "Mymensingh:Bhaluka": "ভালুকা",
  "Mymensingh:Dhobaura": "ধোবাউড়া",
  "Mymensingh:Fulbaria": "ফুলবাড়ীয়া",
  "Mymensingh:Gaffargaon": "গফরগাঁও",
  "Mymensingh:Gauripur": "গৌরীপুর",
  "Mymensingh:Haluaghat": "হালুয়াঘাট",
  "Mymensingh:Ishwarganj": "ঈশ্বরগঞ্জ",
  "Mymensingh:Muktagachha": "মুক্তাগাছা",
  "Mymensingh:Mymensingh Sadar": "ময়মনসিংহ সদর",
  "Mymensingh:Nandail": "নান্দাইল",
  "Mymensingh:Phulpur": "ফুলপুর",
  "Mymensingh:Tarakanda": "তারাকান্দা",
  "Mymensingh:Trishal": "ত্রিশাল",
  "Naogaon:Atrai": "আত্রাই",
  "Naogaon:Badalgachhi": "বদলগাছী",
  "Naogaon:Dhamoirhat": "ধামইরহাট",
  "Naogaon:Manda": "মান্দা",
  "Naogaon:Mahadebpur": "মহাদেবপুর",
  "Naogaon:Naogaon Sadar": "নওগাঁ সদর",
  "Naogaon:Niamatpur": "নিয়ামতপুর",
  "Naogaon:Patnitala": "পত্নিতলা",
  "Naogaon:Porsha": "পোরশা",
  "Naogaon:Raninagar": "রাণীনগর",
  "Naogaon:Sapahar": "সাপাহার",
  "Narail:Kalia": "কালিয়া",
  "Narail:Lohagara": "লোহাগড়া",
  "Narail:Narail Sadar": "নড়াইল সদর",
  "Narayanganj:Araihazar": "আড়াইহাজার",
  "Narayanganj:Bandar": "বন্দর",
  "Narayanganj:Narayanganj Sadar": "নারায়নগঞ্জ সদর",
  "Narayanganj:Rupganj": "রূপগঞ্জ",
  "Narayanganj:Sonargaon": "সোনারগাঁ",
  "Narsingdi:Belabo": "বেলাবো",
  "Narsingdi:Monohardi": "মনোহরদী",
  "Narsingdi:Narsingdi Sadar": "নরসিংদী সদর",
  "Narsingdi:Palash": "পলাশ",
  "Narsingdi:Raipura": "রায়পুরা",
  "Narsingdi:Shibpur": "শিবপুর",
  "Natore:Bagatipara": "বাগাতিপাড়া",
  "Natore:Baraigram": "বড়াইগ্রাম",
  "Natore:Gurudaspur": "গুরুদাসপুর",
  "Natore:Lalpur": "লালপুর",
  "Natore:Natore Sadar": "নাটোর সদর",
  "Natore:Naldanga": "নলডাঙ্গা",
  "Natore:Singra": "সিংড়া",
  "Netrokona:Atpara": "আটপাড়া",
  "Netrokona:Barhatta": "বারহাট্টা",
  "Netrokona:Durgapur": "দুর্গাপুর",
  "Netrokona:Kalmakanda": "কলমাকান্দা",
  "Netrokona:Kendua": "কেন্দুয়া",
  "Netrokona:Khaliajuri": "খালিয়াজুরী",
  "Netrokona:Madan": "মদন",
  "Netrokona:Mohanganj": "মোহনগঞ্জ",
  "Netrokona:Netrokona Sadar": "নেত্রকোণা সদর",
  "Netrokona:Purbadhala": "পূর্বধলা",
  "Nilphamari:Dimla": "ডিমলা",
  "Nilphamari:Domar": "ডোমার",
  "Nilphamari:Jaldhaka": "জলঢাকা",
  "Nilphamari:Kishoreganj": "কিশোরগঞ্জ",
  "Nilphamari:Nilphamari Sadar": "নীলফামারী সদর",
  "Nilphamari:Saidpur": "সৈয়দপুর",
  "Noakhali:Begumganj": "বেগমগঞ্জ",
  "Noakhali:Chatkhil": "চাটখিল",
  "Noakhali:Companiganj": "কোম্পানীগঞ্জ",
  "Noakhali:Hatiya": "হাতিয়া",
  "Noakhali:Kabirhat": "কবিরহাট",
  "Noakhali:Noakhali Sadar": "নোয়াখালী সদর",
  "Noakhali:Senbagh": "সেনবাগ",
  "Noakhali:Sonaimuri": "সোনাইমুড়ী",
  "Noakhali:Subarnachar": "সুবর্ণচর",
  "Pabna:Atgharia": "আটঘরিয়া",
  "Pabna:Bera": "বেড়া",
  "Pabna:Bhangura": "ভাঙ্গুড়া",
  "Pabna:Chatmohar": "চাটমোহর",
  "Pabna:Faridpur": "ফরিদপুর",
  "Pabna:Ishwardi": "ঈশ্বরদী",
  "Pabna:Pabna Sadar": "পাবনা সদর",
  "Pabna:Santhia": "সাঁথিয়া",
  "Pabna:Sujanagar": "সুজানগর",
  "Panchagarh:Atwari": "আটোয়ারী",
  "Panchagarh:Boda": "বোদা",
  "Panchagarh:Debiganj": "দেবীগঞ্জ",
  "Panchagarh:Panchagarh Sadar": "পঞ্চগড় সদর",
  "Panchagarh:Tetulia": "তেতুলিয়া",
  "Patuakhali:Bauphal": "বাউফল",
  "Patuakhali:Dashmina": "দশমিনা",
  "Patuakhali:Dumki": "দুমকি",
  "Patuakhali:Galachipa": "গলাচিপা",
  "Patuakhali:Kalapara": "কলাপাড়া",
  "Patuakhali:Mirzaganj": "মির্জাগঞ্জ",
  "Patuakhali:Patuakhali Sadar": "পটুয়াখালী সদর",
  "Patuakhali:Rangabali": "রাঙ্গাবালী",
  "Pirojpur:Bhandaria": "ভান্ডারিয়া",
  "Pirojpur:Kawkhali": "কাউখালী",
  "Pirojpur:Mathbaria": "মঠবাড়ীয়া",
  "Pirojpur:Nazirpur": "নাজিরপুর",
  "Pirojpur:Nesarabad": "নেছারাবাদ",
  "Pirojpur:Pirojpur Sadar": "পিরোজপুর সদর",
  "Pirojpur:Zianagar": "জিয়ানগর",
  "Rajbari:Baliakandi": "বালিয়াকান্দি",
  "Rajbari:Goalandaghat": "গোয়ালন্দ",
  "Rajbari:Kalukhali": "কালুখালী",
  "Rajbari:Pangsha": "পাংশা",
  "Rajbari:Rajbari Sadar": "রাজবাড়ী সদর",
  "Rajshahi:Bagha": "বাঘা",
  "Rajshahi:Bagmara": "বাগমারা",
  "Rajshahi:Charghat": "চারঘাট",
  "Rajshahi:Durgapur": "দুর্গাপুর",
  "Rajshahi:Godagari": "গোদাগাড়ী",
  "Rajshahi:Mohanpur": "মোহনপুর",
  "Rajshahi:Paba": "পবা",
  "Rajshahi:Puthia": "পুঠিয়া",
  "Rajshahi:Tanore": "তানোর",
  "Rajshahi:Rajshahi City": "রাজশাহী সিটি",
  "Rangamati:Baghaichhari": "বাঘাইছড়ি",
  "Rangamati:Barkal": "বরকল",
  "Rangamati:Belaichhari": "বিলাইছড়ি",
  "Rangamati:Kaptai": "কাপ্তাই",
  "Rangamati:Juraichhari": "জুরাছড়ি",
  "Rangamati:Langadu": "লংগদু",
  "Rangamati:Naniarchar": "নানিয়ারচর",
  "Rangamati:Rajasthali": "রাজস্থলী",
  "Rangamati:Rangamati Sadar": "রাঙ্গামাটি সদর",
  "Rangpur:Badarganj": "বদরগঞ্জ",
  "Rangpur:Gangachara": "গংগাচড়া",
  "Rangpur:Kaunia": "কাউনিয়া",
  "Rangpur:Mithapukur": "মিঠাপুকুর",
  "Rangpur:Pirgachha": "পীরগাছা",
  "Rangpur:Pirganj": "পীরগঞ্জ",
  "Rangpur:Rangpur Sadar": "রংপুর সদর",
  "Rangpur:Taraganj": "তারাগঞ্জ",
  "Satkhira:Assasuni": "আশাশুনি",
  "Satkhira:Debhata": "দেবহাটা",
  "Satkhira:Kalaroa": "কলারোয়া",
  "Satkhira:Kaliganj": "কালিগঞ্জ",
  "Satkhira:Satkhira Sadar": "সাতক্ষীরা সদর",
  "Satkhira:Shyamnagar": "শ্যামনগর",
  "Satkhira:Tala": "তালা",
  "Shariatpur:Bhedarganj": "ভেদরগঞ্জ",
  "Shariatpur:Damudya": "ডামুড্যা",
  "Shariatpur:Gosairhat": "গোসাইরহাট",
  "Shariatpur:Naria": "নড়িয়া",
  "Shariatpur:Shariatpur Sadar": "শরিয়তপুর সদর",
  "Shariatpur:Zanjira": "জাজিরা",
  "Sherpur:Jhenaigati": "ঝিনাইগাতী",
  "Sherpur:Nakla": "নকলা",
  "Sherpur:Nalitabari": "নালিতাবাড়ী",
  "Sherpur:Sherpur Sadar": "শেরপুর সদর",
  "Sherpur:Sreebardi": "শ্রীবরদী",
  "Sirajganj:Belkuchi": "বেলকুচি",
  "Sirajganj:Chauhali": "চৌহালি",
  "Sirajganj:Kamarkhanda": "কামারখন্দ",
  "Sirajganj:Kazipur": "কাজীপুর",
  "Sirajganj:Raiganj": "রায়গঞ্জ",
  "Sirajganj:Shahjadpur": "শাহজাদপুর",
  "Sirajganj:Sirajganj Sadar": "সিরাজগঞ্জ সদর",
  "Sirajganj:Tarash": "তাড়াশ",
  "Sirajganj:Ullapara": "উল্লাপাড়া",
  "Sunamganj:Bishwamberpur": "বিশ্বম্ভরপুর",
  "Sunamganj:Chhatak": "ছাতক",
  "Sunamganj:Derai": "দিরাই",
  "Sunamganj:Dharampasha": "ধর্মপাশা",
  "Sunamganj:Dowarabazar": "দোয়ারাবাজার",
  "Sunamganj:Jagannathpur": "জগন্নাথপুর",
  "Sunamganj:Jamalganj": "জামালগঞ্জ",
  "Sunamganj:Sullah": "শাল্লা",
  "Sunamganj:Sunamganj Sadar": "সুনামগঞ্জ সদর",
  "Sunamganj:Tahirpur": "তাহিরপুর",
  "Sylhet:Balaganj": "বালাগঞ্জ",
  "Sylhet:Beanibazar": "বিয়ানীবাজার",
  "Sylhet:Bishwanath": "বিশ্বনাথ",
  "Sylhet:Companiganj": "কোম্পানীগঞ্জ",
  "Sylhet:Fenchuganj": "ফেঞ্চুগঞ্জ",
  "Sylhet:Golapganj": "গোলাপগঞ্জ",
  "Sylhet:Gowainghat": "গোয়াইনঘাট",
  "Sylhet:Jaintiapur": "জৈন্তাপুর",
  "Sylhet:Kanaighat": "কানাইঘাট",
  "Sylhet:Osmani Nagar": "ওসমানী নগর",
  "Sylhet:Sylhet Sadar": "সিলেট সদর",
  "Sylhet:Zakiganj": "জকিগঞ্জ",
  "Tangail:Basail": "বাসাইল",
  "Tangail:Bhuapur": "ভুয়াপুর",
  "Tangail:Delduar": "দেলদুয়ার",
  "Tangail:Dhanbari": "ধনবাড়ী",
  "Tangail:Ghatail": "ঘাটাইল",
  "Tangail:Gopalpur": "গোপালপুর",
  "Tangail:Kalihati": "কালিহাতী",
  "Tangail:Madhupur": "মধুপুর",
  "Tangail:Mirzapur": "মির্জাপুর",
  "Tangail:Nagarpur": "নাগরপুর",
  "Tangail:Sakhipur": "সখিপুর",
  "Tangail:Tangail Sadar": "টাঙ্গাইল সদর",
  "Thakurgaon:Baliadangi": "বালিয়াডাঙ্গী",
  "Thakurgaon:Haripur": "হরিপুর",
  "Thakurgaon:Pirganj": "পীরগঞ্জ",
  "Thakurgaon:Ranisankail": "রাণীশংকৈল",
  "Thakurgaon:Thakurgaon Sadar": "ঠাকুরগাঁও সদর"
};

export function districtLabel(district: string) {
  const bengali = DISTRICT_BN[district];
  return bengali ? `${district} (${bengali})` : district;
}

export function thanaLabel(district: string, thana: string) {
  const bengali = THANA_BN[`${district}:${thana}`];
  return bengali ? `${thana} (${bengali})` : thana;
}
