// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://exttnjcgwfqoabyvnya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_fAjNEI2AZ-EXalXJugvyOw_RvLXaaCx";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  },
});